name = "Cloudstead Modpack"
author = "luigistyle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82d39437c983f3b4725c6d3a19b421d12cfcf69feb93e5ff67d2a073926791e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
