name = "Cloudstead Modpack"
author = "luigistyle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4329098a7f9661964a68bd61b8c5f28554e8884a33315eef95fb3a0ee4c9a570"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
