name = "Cloudstead Modpack"
author = "luigistyle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddfbe4fdc4d7d3ac8039a60c63dc99dd644ba4a2e983c1d7025ccdb39f57f4fa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
